# GitHub Action workflow to build the HoneySAP docker image
#

name: Build HoneySAP docker image

on: [push, pull_request]

env:
   DOCKER_TAG: honeysap:development

jobs:
  build:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout HoneySAP
        uses: actions/checkout@v4
      - name: Build docker image
        run: |
          docker build -t ${DOCKER_TAG} -f deployment/Dockerfile .
